package com.SushiAPI.SushiAPI.controller.API.Cart;

import com.SushiAPI.SushiAPI.models.Item;
import com.SushiAPI.SushiAPI.utils.CartService;
import com.SushiAPI.SushiAPI.utils.MenuServices;
import org.json.JSONObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

@RestController
public class CartController { // add userId generated by sessionId
    @GetMapping("/api/cart")
    public ResponseEntity<List<Item>> getMenu() {
        List<Item> items = CartService.allItems();
        return new ResponseEntity<List<Item>>(items, HttpStatus.OK);
    }

    @PostMapping("/api/cart/add")
    public boolean addItem(@RequestBody String addItem) {
        JSONObject jsonObject = new JSONObject(addItem);
        Item item = new Item(jsonObject.getString("name"),jsonObject.getDouble("price"),jsonObject.getBoolean("isDrink"), jsonObject.getBoolean("isHot"), jsonObject.getBoolean("isAppetizer"), jsonObject.getBoolean("isRaw"));
        CartService.addItem(item);
        return true;
    }

    @PostMapping("/api/cart/remove")
    public boolean removeItem(@RequestBody String removeItem) {
        JSONObject jsonObject = new JSONObject(removeItem);
        Item item = new Item(jsonObject.getString("name"),jsonObject.getDouble("price"),jsonObject.getBoolean("isDrink"), jsonObject.getBoolean("isHot"), jsonObject.getBoolean("isAppetizer"), jsonObject.getBoolean("isRaw"));
        CartService.removeItem(item);
        return true;
    }

    @GetMapping("/api/cart/search")
    public ResponseEntity<List<Item>> searchCart(@RequestBody String searchItem) {
        JSONObject jsonObject = new JSONObject(searchItem);
        List<Item> items = CartService.searchItems(jsonObject.getString("query"));
        return new ResponseEntity<List<Item>>(items, HttpStatus.OK);
    }

}
